name: iOS SDK Release

on:
  workflow_call:
    inputs:
      dryRun:
        description: Do a dry run to preview instead of a real release [true/false]
        type: string
        required: true
        default: "true"

jobs:
  # SDK release is done from main branch.
  confirm-main-branch:
    name: "Confirm release is run from main branch"
    uses: mParticle/mparticle-workflows/.github/workflows/sdk-release-repo-branch-check.yml@stable

  create-release-branch:
    name: Create release branch
    runs-on: macOS-latest
    needs: confirm-main-branch
    steps:
      - name: Checkout development branch
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.MP_INTEGRATIONS_SEMANTIC_RELEASE_BOT }}
          ref: development

      - name: Create and push release branch to repository
        run: |
          git checkout -b release/${{ github.run_number }}
          git push origin release/${{ github.run_number }}

  release:
    name: Perform release
    runs-on: macOS-latest
    needs: create-release-branch
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.MP_INTEGRATIONS_SEMANTIC_RELEASE_BOT }}
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate environment
        run:
          env | grep -q '^GITHUB_ACCESS_TOKEN=' || (echo "Required environment variable GITHUB_ACCESS_TOKEN is not set" && exit 1)
          env | grep -q '^COCOAPODS_TRUNK_TOKEN=' || (echo "Required environment variable COCOAPODS_TRUNK_TOKEN is not set" && exit 1)

      - name: Setup git config
        run: |
          git config user.email "developers@mparticle.com"
          git config user.name "mParticle Automation"

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          token: ${{ secrets.MP_INTEGRATIONS_SEMANTIC_RELEASE_BOT }}
          ref: main

      - name: Merge release branch into main branch
        run: |
          git pull origin release/${{ github.run_number }}

      - name: Pull down and modify release.js and release scripts
        run: |
          curl --progress-bar -O https://raw.githubusercontent.com/mParticle/mparticle-workflows/main/ios/release.config.js
          curl --progress-bar -O https://raw.githubusercontent.com/mParticle/mparticle-workflows/main/ios/release.sh
          sed -i '' "s/REPO_NAME/$(ls *.podspec | sed 's/.podspec//')/g" release.config.js

      - name: Release --dry-run
        if: ${{ github.event.inputs.dryRun == 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.MP_INTEGRATIONS_SEMANTIC_RELEASE_BOT }}
          GIT_AUTHOR_NAME: mparticle-bot
          GIT_AUTHOR_EMAIL: developers@mparticle.com
          GIT_COMMITTER_NAME: mparticle-bot
          GIT_COMMITTER_EMAIL: developers@mparticle.com
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @semantic-release/exec@5 \
          semantic-release --dry-run

      - name: Release
        if: ${{ github.event.inputs.dryRun == 'false'}}
        env:
          GITHUB_TOKEN: ${{ secrets.MP_INTEGRATIONS_SEMANTIC_RELEASE_BOT }}
          GIT_AUTHOR_NAME: mparticle-bot
          GIT_AUTHOR_EMAIL: developers@mparticle.com
          GIT_COMMITTER_NAME: mparticle-bot
          GIT_COMMITTER_EMAIL: developers@mparticle.com
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @semantic-release/exec@5 \
          semantic-release

      - name: Push automated release commits to release branch
        if: ${{ github.event.inputs.dryRun == 'false' }}
        run: |
          ls 
          git status
          git push origin HEAD:release/${{ github.run_number }}

      - name: Release to CocoaPods
        if: ${{ github.event.inputs.dryRun == 'false'}}
        run: |
          sudo gem install xcodeproj
          pod trunk push --allow-warnings

  finalize-release:
    name: Finalize release
    needs: release
    runs-on: macOS-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          token: ${{ secrets.MP_INTEGRATIONS_SEMANTIC_RELEASE_BOT }}
          ref: main

      - name: Merge release branch into main branch
        if: ${{ github.event.inputs.dryRun == 'false' }}
        run: |
          git pull origin release/${{ github.run_number }}

      - name: Push release commits to main and development branches
        if: ${{ github.event.inputs.dryRun == 'false'}}
        run: |
          git push origin HEAD:main
          git push origin HEAD:development

      - name: Delete release branch
        if: ${{ github.event.inputs.dryRun == 'false' }}
        run: |
          git push --delete origin release/${{ github.run_number }}